services:
  filesystem_connector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "{{ cookiecutter.connector_port }}:{{ cookiecutter.connector_port }}"
    #volumes:
        # map any external folders
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
      - DSXCONNECTOR_CONNECTOR_URL=http://{{ cookiecutter.__release_name }}-api:{{ cookiecutter.connector_port }} # see aliases below
      - DSXCONNECTOR_DSX_CONNECT_URL=http://dsx-connect-api:8586 # note, this works if running on the same internal network on Docker as the dsx_connect_core...
      - DSXCONNECTOR_LOCATION=/app/scan_folder
      - DSXCONNECTOR_ITEM_ACTION=nothing
    networks:
      dsx-network:
        aliases:
          - {{ cookiecutter.__release_name }}-api  # this is how dsx-connect will communicate with this on the network
    command:
      python connectors/{{ cookiecutter.project_slug }}/{{ cookiecutter.project_slug }}_connector.py

# The following assumes an already created docker network like this:
# docker network create dsx-connect-network --driver bridge
networks:
    dsx-network:
      external: true
      name: dsx-connect-network  # change this to an existing docker network
